version: '3.3'

services:
  db:
    image: mariadb:10.5
    volumes:
      - db_data:/var/lib/mysql
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: altiusbasketball
      MYSQL_DATABASE: altiusbasketball
      MYSQL_USER: altiusbasketball
      MYSQL_PASSWORD: altiusbasketball

  wordpress:
    depends_on:
      - db
    image: wordpress:6.5.3-php8.3-apache
    ports:
      - "8000:80"
    restart: always
    volumes:
      - ./altiusbasketball:/var/www/html/wp-content/themes/altiusbasketball
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: altiusbasketball
      WORDPRESS_DB_PASSWORD: altiusbasketball
      WORDPRESS_DB_NAME: altiusbasketball

volumes:
  db_data: {}
